# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bade1346ff6ff740bbbf2857821b6f03f748d82baa89791a6dd3f34df4512ca9d5b260a2d4f5120a381a221904d16dc20fb48d66c06cc006b82c81163b894d76

test:
  secret_key_base: 6ed1405821ff3a7fddeb08c306c2a84042023961ad4ef659615bd65ae1c84a21dc5bc1845dbd4451e50e3aca340bff6c114c4d4f5c5e364fbcfe97873ac7bf25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
